### ISSUE TITLE
Issue in api.js

### ISSUE THREAD

**Issue by IDK-TERADA** [bitfocus/companion-module-idk-ninjar#1]
In the getData method of api.js, a series of status retrieval commands are sent consecutively. What are these commands used for?

Also, since the device does not receive a response before the next command is processed, a timeout error occurs. As a result, commands assigned to buttons are not sent.

Relevant code section:
getData() {
    let self = this;
    for (let i = 1; i < 512; i++) {
        self.sendCommand(`@GSVC,0,0,1,${i}`); // get video input of output i
        self.sendCommand(`@GSAC,0,0,1,${i}`); // get audio input of output i
        self.sendCommand(`@GCHS,1,${i},0`); // get input status
        self.sendCommand(`@GCHS,2,${i},0`); // get output status
    }    
},

**Comment by josephdadams** [comment]
It is used to keep the module in sync with the device.

We can implement a command queue where the module does not send a command until it receives a response of some kind to the previous one.

**Comment by IDK-TERADA** [comment]
@josephdadams 

Thank you for the explanation. I understand now.

Regarding the implementation of the command queue, should we proceed with it on our end, or will it be handled on your side?

If we are to proceed with the changes, could you also provide specific instructions for the process after implementing them, such as committing and creating a pull request on GitHub? Your guidance would be greatly appreciated. Thank you for your assistance.

**Comment by josephdadams** [comment]
Submit a pull request, I will review and merge. When we are ready for a release to Companion, I can tag those and put them in for you.

**Comment by IDK-TERADA** [comment]
I commented out self.getData() on line 23 of api.js, and it worked, which led me to believe that this was the issue. However, I have been unable to resolve it. The logs indicate the following repeating errors:

Logs：
error: Error getting config fields: Call timed out
error: Module registration failed Error: Call timed out
    at IpcWrapper.sendWithCb (C:\companion-module-dev\companion-module-dev\companion-module-idk-ninjar-main\node_modules\@companion-module\base\dist\host-api\ipc-wrapper.js:39:30)
    at C:\companion-module-dev\companion-module-dev\companion-module-idk-ninjar-main\node_modules\@companion-module\base\dist\entrypoint.js:112:20
Starting up module class: ninjarInstance

Could you please assist me with this issue?

**Comment by josephdadams** [comment]
What kind of response does the device give when each command is sent? Is there any kind of ACK sent? We will need to know what a valid response looks like in order to implement a command queue.

**Comment by IDK-TERADA** [comment]
After analyzing the packets with Wireshark, we confirmed that the sending and receiving of each command is functioning correctly. Therefore, the error is likely occurring in the async processData(data) section rather than in the communication segment.

As a result, I will close this issue and open a new thread for further discussion.
