### ISSUE TITLE
Request to Add Video & Audio Switching Action

### ISSUE THREAD

**Issue by IDK-TERADA** [bitfocus/companion-module-idk-ninjar#2]
Description: Currently, there are separate switching actions for Video and Audio. We would like to request the addition of an action that switches both Video and Audio simultaneously.

Command:
@SSW,0,0,1,{inputChannel},{outputChannel}

**Comment by josephdadams** [comment]
Done in https://github.com/bitfocus/companion-module-idk-ninjar/commit/3e4b869caae689fa8bda440e1461b467efab97b5
